name: Code Coverage
on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pylint
          pip install -U Flask
          pip install -U flask-cors
          pip install pytest
          pip install pytest-cov
          pip install -r ./requirements.txt

      - name: Run tests and generate coverage
        env:
          api_key: ${{ secrets.api_key }}
        run: |
          cd test
          coverage run -m unittest discover -s test
          coverage report

      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
