name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pylint
        pip install -U Flask
        pip install -U flask-cors
        pip install -r ./requirements.txt
    - name: Running test cases for searching
      run: python test/test_search.py
    - name: Running test cases for util
      run: python test/tests.py
    - name: Running test cases for api
      env: 
        api_key: ${{ secrets.api_key }}
      run: python test/test_api.py
